service: dictbot

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  environment: ${file(env.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lex:PostContent"
        - "lex:PostText"
        - "polly:SynthesizeSpeech"
      Resource: "*"
    - Effect: "Allow"
      Action:
        #       - "s3:PutObjectAcl"
        - "s3:ListAllMyBuckets"
        - "s3:ListBucket"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "*"
#      Resource:
#        'Fn::ImportValue': dictbot-s3-polly-cache-bucket

package:
  exclude:
    - '.*'
    - '*.iml'
    - 'env.yml*'
    - 'cloudformation/*'
    - 'data/*'
    - 'utils/*'

functions:
  facebook-get:
    handler: facebook.get
    description: GET handler for verification
    memorySize: 128
    timeout: 5
    events:
      - http: GET /
  facebook-post:
    handler: facebook.post
    description: POST handler for receiving and sending json
    memorySize: 128
    timeout: 35
    events:
      - http: POST /
  lex-handler:
    handler: lex.handler
    description: Lex handler
    memorySize: 128
    timeout: 30
    environment:
      POLLY_CACHE_S3_ARN:
        'Fn::ImportValue': dictbot-s3-polly-cache-bucket

resources:
  Resources:
    FacebookDashgetLogGroup:
      Properties:
        RetentionInDays: 7
    FacebookDashpostLogGroup:
      Properties:
        RetentionInDays: 7
    LexDashhandlerLogGroup:
      Properties:
        RetentionInDays: 7
